server:
  port: 8088
spring:
  application:
    name: gateway-app
  cloud:
    gateway:
      routes:
        - id: microservice1
          uri: lb://microservice1-app
          predicates:
            - Path=/microservice1-endpoint
        - id: microservice2
          uri: lb://microservice2-app
          predicates:
            - Path=/microservice2-endpoint